### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by SaSa709** [lxxcontinue/SSCOR#2]
when i run restore.py in my windows, i found bug "FileNotFoundError: [Errno 2] No such file or directory: './checkpoints\\MPM_stripe_1\\latest_net_G_A.pth'"

i tried to use docker in ubuntu 20.04 and found the same error "FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/MPM_stripe_1/latest_net_G_A.pth'"

i cannot generate 'latest_net_G_A.pth' ,how should i do?
thank you!

**Comment by lxxcontinue** [comment]
The "latest_net_G_A.pth" file can only be generated after training is completed. You need to first run the sampling script to sample patches and thus create the training set. Then you can train the model based on the sampled patches.
